### ISSUE TITLE
RGB image

### ISSUE THREAD

**Issue by ghorbelm** [EvolvedSquid/tutorials#11]

**Comment by sebtheiler** [comment]
I'm sorry it's taken me a full week to respond - lot's of stuff has been going on recently and it's been year since I last worked on this so I'm a bit rusty.

In your original comment, I saw you changed `INPUT_SHAPE`, but did you also change the `process_frame` function in `train_dqn.py` to *not grayscale the image*?  IIRC, you can make it not grayscale the image by removing `frame = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)`
